### ISSUE TITLE
Dad should inform us of upgrades

### ISSUE THREAD

**Issue by I-question-this** [I-question-this/red-bot-dad-cog#101]
It would be amusing if Dad would inform people of upgrades with this image [here](https://i.imgur.com/Z5mgPhV.jpg).
Ideally this would occur at startup. This could work via actually assigning version numbers to Dad, and recording in the server config the latest seen version. When Dad starts up he'll check if the current version is later than what he's previously run, and if so he'll post something about it.

**Comment by stegnerw** [comment]
@I-question-this Will we start using the `master` branch when we add this? Also, we should change `master` to `main` to get with the times. It's `time.current_year` after all!

**Comment by I-question-this** [comment]
I agree with this idea.

**Comment by I-question-this** [comment]
Fails to send to multiple servers.

**Comment by I-question-this** [comment]
Still has an error, but only for some servers. Further investigation is needed.

**Comment by I-question-this** [comment]
Nevermind, the error was in not reloading the module.
