### ISSUE TITLE
Society

### ISSUE THREAD

**Issue by I-question-this** [I-question-this/red-bot-dad-cog#104]
Dad should respond with gifs about "society" when "society" is mentioned. We do truly live in one. Please also include references to "gamers rising up" and "bottom text".

**Comment by stegnerw** [comment]
I think it would be epic if Dad also gave the society joke the society emote. I'm going to add that and we can remove it later.

**Comment by I-question-this** [comment]
It could be coded so that if the "soceity" emote doesn't exist on the server it just uses the standard clown one.

**Comment by stegnerw** [comment]
> It could be coded so that if the "soceity" emote doesn't exist on the server it just uses the standard clown one.

That's a good idea, although I'm still not sure how to add emotes by name. I looked at Dad's current emote usage and it seems to be done by copy/pasting the glyphs for the emotes. Do you have any ideas on this? @I-question-this

**Comment by I-question-this** [comment]
I figured it out! Based on this [stackover flow article](https://stackoverflow.com/questions/48982061/how-do-you-have-a-bot-add-a-reaction-using-a-custom-emoji) and the [discord.py documentation for the Guild object](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.emojisl)
I was able to create the following:
```python
society_emoji = discord.utils.get(msg.channel.guild.emojis, 
        name="society")
if society_emoji:
    await msg.add_reaction(society_emoji)
else:
    await msg.add_reaction("🤡")
```
as seen in a696a59d1c6d3fcb896f0cda2b9d4a2efc9ad726

**Comment by stegnerw** [comment]
> I figured it out! Based on this [stackover flow article](https://stackoverflow.com/questions/48982061/how-do-you-have-a-bot-add-a-reaction-using-a-custom-emoji) and the [discord.py documentation for the Guild object](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.emojisl)
> I was able to create the following:
> 
> ```python
> society_emoji = discord.utils.get(msg.channel.guild.emojis, 
>         name="society")
> if society_emoji:
>     await msg.add_reaction(society_emoji)
> else:
>     await msg.add_reaction("🤡")
> ```
> 
> as seen in [a696a59](https://github.com/I-question-this/red-bot-dad-cog/commit/a696a59d1c6d3fcb896f0cda2b9d4a2efc9ad726)

Awesome, I am unable to test currently but if that feature works it should be ready for a pull request after setting the appropriate joke probability.

**Comment by I-question-this** [comment]
I feel like 100 is appropriate for this.
