### ISSUE TITLE
Let Dad respond with some cowsay goodness

### ISSUE THREAD

**Issue by king2b3** [I-question-this/red-bot-dad-cog#113]
Use subprocess to take a message from discord, run it through cowsay, and then send the message back to discord.

We should re-build cowsay for this.

Maybe a pengin-wengie?

**Comment by I-question-this** [comment]
This should have the following specs:
- [ ] The speech is constructed in a separate method
- [ ] Construction of the cow is in it's own method that can be hot swapped with other ASCII art animals
- [ ] Will simply replay a message back at a user but in the speech bubble, like with spongebob
- [ ] Should also be callable as a standalone command so users can request a message be "cowsay"ed.

**Comment by I-question-this** [comment]
As it currently stands it's a bit...troublesome. I'm currently containing it within the `codeblock` structure of Discord markdown, which preserves the spacing on Desktop, but not so much on mobile. Additionally, the `codeblock` structure makes emojies not work as well or at all. More work is required.
