### ISSUE TITLE
Add "Senpai notice me" meme

### ISSUE THREAD

**Issue by mayersjd** [I-question-this/red-bot-dad-cog#47]
We can make dad notice his children when they request it. Maybe throw in some of those UwU gifs

**Comment by I-question-this** [comment]
@mayersjd I've added an interpretation in which users saying "senpai notice me" get a gif of others desiring to be noticed. How do you feel about this in terms of your original idea?

**Comment by I-question-this** [comment]
@mayersjd said offline that this is a sufficient interpretation of his idea and this issue can thus be closed.
