### ISSUE TITLE
That's fair

### ISSUE THREAD

**Issue by I-question-this** [I-question-this/red-bot-dad-cog#64]
The following has been brought to our attention by @king2b3
![image](https://user-images.githubusercontent.com/9321869/92985588-08df5000-f482-11ea-86c5-06b8fec44933.png)

It has become an infectious disease in our consciousness. The only thing that can be done is to propagate it further, the question remains on how to do so. It is thus still up for discussion on how it should be implemented, particularly in how it should be triggered.

**Comment by king2b3** [comment]
x%that Dad reacts with "That's fair" to any message

**Comment by I-question-this** [comment]
In addition to it being a random chance it shall also be that one will become "the fair child" the fair child will have their messages responded to with "that's fair" N times. If someone else happens to become the fair child before the N responses then the first person is let off early.
