### ISSUE TITLE
Add "bonk" features to dad

### ISSUE THREAD

**Issue by king2b3** [I-question-this/red-bot-dad-cog#89]
If someone gets a little naughty, they will be bonked into horny jail.
<img width="707" alt="Screen_Shot_2020-04-28_at_12 21 48_PM" src="https://user-images.githubusercontent.com/38116599/98125511-920f7380-1e82-11eb-8f3d-d0aefcd00a12.png">

A list of words will be chosen for this

**Comment by stegnerw** [comment]
@king2b3 Can we change the naming on this joke? The functionality is fine, but I wanted to add a feature to have dad react to the word "bonk" with bonk gifs, and I was going to call that bonk.py... Wouldn't make sense under any other name tbh...

**Comment by king2b3** [comment]
@stegnerw I have modified the code to now respond to the keyword "bonk" in the meantime, while the profanity_check library is being fixed.

**Comment by I-question-this** [comment]
@stegnerw You are welcome to refactor the bonk joke to be a different name and implement a singularly "bonk" feature.
