### ISSUE TITLE
Change hard-coded profanity to the profanity module

### ISSUE THREAD

**Issue by I-question-this** [I-question-this/red-bot-dad-cog#91]
@king2b3 brought to our attention the [profanity-check](https://pypi.org/project/profanity-check/) module in his implementation of #89 in pull-request #90. This should now be used by the favoritism joke to determine rather a user is being profane towards Dad. This will still be the simple method of ``profane word & Dad's name => profane to Dad``, but will include the more robust method of determining bad words. This will also require updating the method `` explain_points`` command to explain how Dad determines bad words.

- [ ] Update favoritism to use [profanity-check](https://pypi.org/project/profanity-check/)
- [ ] Update ``explain_points`` command to explain that [profanity-check](https://pypi.org/project/profanity-check/) is used

**Comment by king2b3** [comment]
This is going to have to wait until the profanity check library passes its current build, at the moment it is failing.

**Comment by I-question-this** [comment]
Since profanity-check has shown itself to be unreliable for so long this issue will be closed. If working improvement to the hard-coded list is found in the future then that should be used.
